### ISSUE TITLE
[BUG]: Cannot transfer entire balance

### ISSUE THREAD

**Issue by koignettt** [koinos/koinos-cli#141] opened 2022-11-09 12:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Transferring the entire balance of an account results in an insufficient balance error.

https://github.com/koinos/koinos-cli/blob/master/internal/cli/commands.go#:~:text=//%20Ensure%20a%20transfer%20greater%20than%20opened,%7D

### Expected behavior

The entire balance of an account should be transferrable.

### Steps to reproduce

Transfer the entire balance of one account to a second account.
The transfer verb errors with an insufficient balance error.

### Environment

```markdown
- OS:
```

**Comment by sgerbino** [comment] 2022-11-17 02:47
Because it costs mana to execute a transfer and transferring all your KOIN would result in you having no mana, you cannot perform this action. If you'd like to transfer your entire balance, you'd have to get another account to pay the mana for you.

This is by design. Hope that helps.

**Closed by sgerbino** 2022-11-17 02:47 UTC
Labels: bug
